version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres:11.3-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: unless-stopped
    volumes:
      - ./postgres/postgres_data:/var/lib/postgresql/data/
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
  
  nginx:
    build: ./nginx
    ports:
     - 31337:80
    depends_on:
    - flask-web
    restart: unless-stopped

  flask-web:
    build: ./strongbox
    command: gunicorn --bind 0.0.0.0:5000 app:app
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./strongbox/app:/app
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
